version: '2.0'

services:
  api:
    build: todos-api
    command: "npm start"
    environment:
      - NODE_ENV=local
    ports:
      - "${API_PORT}:7000"
    #user: "root"
    networks:
      - main
    volumes:
      - ./todos-api:/home/node/app
      - /home/node/app/node_modules

  front:
    build: todos-fe
    command: "npm start"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    ports:
      - "${FRONT_PORT}:4200"
    #user: "root"
    networks:
      - main
    volumes:
      - ./todos-fe:/home/node/app
      - /home/node/app/node_modules
  
  proxy:
    build: proxy
    depends_on:
      - api
      - front
    networks:
      - main
    ports:
      - "${PROXY_PORT}:80"

  magneto-web:
    build: magneto-web
    ports:
      - "${BACK_PORT}:80"
    tty: true
    restart: always
    networks:
        - main
    volumes:
      - ./magneto-web/htdocs:/var/www/html
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: samplest_magento
      DB_USERNAME: ranosys
      DB_PASSWORD: ranosys@123
  mysql:
    image: mysql:5.7
    restart: always
    networks:
        - main
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: samplest_magento
      MYSQL_USER: ranosys
      MYSQL_PASSWORD: ranosys@123
      MYSQL_ROOT_PASSWORD: ranosys@123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge-4.8
    container_name: phpmyadmin
    environment:
        PMA_ARBITRARY: 0
        PMA_HOST: "mysql"
        PMA_PORT: 3306
        PMA_USER: "ranosys"
        PMA_PASSWORD: "ranosys@123"
    restart: always
    ports:
        - "${PMA_PORT}:80"
    links:
        - mysql
    volumes:
        - /sessions
    networks:
      - main

networks:
  main:
    driver: bridge